// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBouyAOALeFsBM7eD_eiiWbAkoPaZmIjTM',
    appId: '1:175898014545:web:4a72a4bd4d741ef7de1970',
    messagingSenderId: '175898014545',
    projectId: 'gate-f4631',
    authDomain: 'gate-f4631.firebaseapp.com',
    storageBucket: 'gate-f4631.firebasestorage.app',
    measurementId: 'G-91KBL6Q9QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK5RKcNlwsZZX9Ug0XyRk1-6rhG2tvbno',
    appId: '1:175898014545:android:df789291b7413704de1970',
    messagingSenderId: '175898014545',
    projectId: 'gate-f4631',
    storageBucket: 'gate-f4631.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvLxWM9YC03r-1HqlD0s_fSGqPG3jXRfE',
    appId: '1:175898014545:ios:26e3e3308f81bc32de1970',
    messagingSenderId: '175898014545',
    projectId: 'gate-f4631',
    storageBucket: 'gate-f4631.firebasestorage.app',
    iosBundleId: 'com.example.gate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvLxWM9YC03r-1HqlD0s_fSGqPG3jXRfE',
    appId: '1:175898014545:ios:26e3e3308f81bc32de1970',
    messagingSenderId: '175898014545',
    projectId: 'gate-f4631',
    storageBucket: 'gate-f4631.firebasestorage.app',
    iosBundleId: 'com.example.gate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBouyAOALeFsBM7eD_eiiWbAkoPaZmIjTM',
    appId: '1:175898014545:web:488b679df24fb7d3de1970',
    messagingSenderId: '175898014545',
    projectId: 'gate-f4631',
    authDomain: 'gate-f4631.firebaseapp.com',
    storageBucket: 'gate-f4631.firebasestorage.app',
    measurementId: 'G-C7X5DBSC3K',
  );
}
